### ISSUE TITLE
how to install cv2 library in python? i am getting this error

### ISSUE THREAD

**Issue by sangyan11** [shailypriya/cartoon_picture#2]
![image](https://user-images.githubusercontent.com/66663381/92114568-aac1c580-ee0e-11ea-9f11-57bce40587c0.png)

**Comment by habelash** [comment]
Use  ** pip install opencv-python**

**Comment by habelash** [comment]
Use **pip install opencv-python**

Actually the **ERROR** is not because of cv2 , there is error in the program when giving the image name in main.py , change the  image name in main.py from **pic.jpg** to **main.jpg** it will work.
